# Generated by Django 4.0.6 on 2022-07-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_datam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataM',
        ),
    ]
